[app]
seed = 8675309
outfile = "demo.png"
width = 1400
height = 1400

[app.colors]
dir = "."
preferred = ["rose", "cerulean"] # Select randomly for these if they're available. When left empty, randomly select from all discovered choices.

[app.style.linenoise]
weight = 100

[app.style.blackhole]
